### ISSUE TITLE
Update/Port over documentation

### ISSUE THREAD

**Issue by jkoritzinsky** [justaprogrammer/BuildCrossCheck#132]
I was just looking at integrating this project into my build pipeline, but I can't seem to find any documentation on how to do so. All of the links are broken for documentation in the README files in each of the repos.

**Comment by StanleyGoldman** [comment]
Hey @jkoritzinsky you caught me in the middle of reworking a lot of my functionality.
I should be cleaned up better soon.

**Comment by StanleyGoldman** [comment]
I'll update you via this issue when I think it's ready for public consumption again.

**Comment by StanleyGoldman** [comment]
Hey @jkoritzinsky I've put together a chunk of documentation that I'm still filling in.
https://github.com/justaprogrammer/BuildCrossCheck/blob/master/docs/integrating.md
Please let me know how your integration efforts go and what points of documentation are weak.
