### ISSUE TITLE
Add a versioning system integrated with AppVeyor

### ISSUE THREAD

**Issue by StanleyGoldman** [justaprogrammer/BuildCrossCheck#50]

**Comment by devlead** [comment]
Using something like Cake.Recipe and following it's conventions could help with this.
https://github.com/cake-contrib/Cake.Recipe/

Example usage:
https://github.com/cake-contrib/Cake.MicrosoftTeams/blob/master/setup.cake

Docs at:
https://cake-contrib.github.io/Cake.Recipe/docs/
